version: '3.9'

services:

  db:
    image: postgres:14-alpine
    container_name: dbCont
    restart: always
    # use different exposed port from "5432" to anything else because "5432" is desired for the pgAdmin
    ports:
      - "5555:5432"

    # change the volume place everytime you -up- the same docker compose
    # or delete the volume everytime you -up- it
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data3
    environment:
      - POSTGRES_DB=reshare_db
      - POSTGRES_USER=reshare
      - POSTGRES_PASSWORD=reshare