version: '3.9'

services:

  db:
    image: postgres:14-alpine
    container_name: dbCont
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reshare_pg
      - POSTGRES_PASSWORD=reshare_123
      - POSTGRES_DB=reshare_db