server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/reshare_db
    username: reshare
    password: reshare
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

